name: Build driver solution
on:
  push:

jobs:
  build-argb-driver:
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x64]
    runs-on: windows-2022

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore dependencies
        run: nuget restore FrameworkArgb\FrameworkArgb.sln

      - name: Build solution
        run: |
          msbuild FrameworkArgb\FrameworkArgb.sln /property:Configuration=${{ env.Configuration }} /property:Platform=${{ env.Platform }}
        env:
          Configuration: ${{ matrix.configuration }}
          Platform: ${{ matrix.platform }}

      # Need to EV sign and replace existing signatures
      # java -jar ~/Downloads/jsign-7.1.jar --replace --storetype PIV --storepass ****** --tsaurl http://ts.ssl.com --tsmode RFC3161 \
      #   FrameworkArgb.dll
      # java -jar ~/Downloads/jsign-7.1.jar --replace --storetype PIV --storepass ****** --tsaurl http://ts.ssl.com --tsmode RFC3161 \
      #   frameworkargb.cat
      - name: Create bundle
        run: |
          mkdir bundle
          cp FrameworkArgb\install\devcon.exe bundle\
          cp FrameworkArgb\install\install_argb_driver.bat bundle\
          cp FrameworkArgb\x64\${{ matrix.configuration }}\FrameworkArgb\frameworkargb.cat bundle\
          cp FrameworkArgb\x64\${{ matrix.configuration }}\FrameworkArgb\FrameworkArgb.dll bundle\
          cp FrameworkArgb\x64\${{ matrix.configuration }}\FrameworkArgb\FrameworkArgb.inf bundle\
          cp FrameworkArgb\x64\${{ matrix.configuration }}\FrameworkArgb.pdb bundle\
          cp FrameworkArgb\x64\${{ matrix.configuration }}\Installer.exe bundle\
          cp FrameworkArgb\x64\${{ matrix.configuration }}\Installer.pdb bundle\

      - name: Upload bundle
        uses: actions/upload-artifact@v4
        with:
          name: framework_win_argb_${{ matrix.configuration }}
          path: bundle

  codeql:
    runs-on: windows-2022
    permissions:
      security-events: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: cpp

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore dependencies
        run: nuget restore FrameworkArgb\FrameworkArgb.sln

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build solution
        run: |
          msbuild FrameworkArgb\FrameworkArgb.sln /property:Configuration=Release /property:Platform=x64

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v4
        with:
          output: sarif-results

      - name: Upload SARIF file
        uses: actions/upload-artifact@v4
        with:
          name: codeql-sarif
          path: sarif-results

      - name: Generate DVL
        shell: cmd
        run: |
          "C:\Program Files (x86)\Windows Kits\10\Tools\dvl\dvl.exe" /manualCreate FrameworkArgb X64 /sarifPath sarif-results

      - name: Upload DVL
        uses: actions/upload-artifact@v4
        with:
          name: dvl
          path: sarif-results/FrameworkArgb.DVL.XML
